site_name: Persson Group Handbook

theme: yeti

nav:
  # - Home: 'index.md'
  - Getting Started:
    - Before you Arrive: 'getting_started/before.md'
    - After you Arrive: 'getting_started/after.md'
    - Getting Settled: 'getting_started/settling.md'
  - Group Policies:
    # - General: 'policies/general.md'
    - Purchasing: 'policies/purchasing.md'
    - Travel: 'policies/travel.md'
  - Computing:
    - General Info: 'computing/computing.md'
    - Software: 'computing/software.md'
    - HPC: 'computing/hpc.md'
    - Atomate Setup: 'computing/atomate.md'
    - Calculation Software: 'computing/calculation_software.md'
  - About:
    - General: 'about/about.md'
    - Subgroup Meetings: 'about/subgroup.md'
    - Group Jobs: 'about/group_jobs.md'
    - Acknowlegements: 'acknowlegements.md'
  # - Students:
  #   - Establishing Residency: 'students/residency.md'
  # - Post-Docs: 'postdocs.md'

markdown_extensions:
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'

extra_css:
  - 'css/code-tabs.css'
