site_name: Persson Group Handbook

nav:
  # - Home: 'index.md'
  - About:
    - General: 'about/about.md'
    - Group Policies: 'about/group_policies.md'
    - Group Jobs: 'about/group_jobs.md'
  - Getting Started:
    - Newcomers: 'getting_started/newcomers.md'
    - Purchasing a Computer: 'getting_started/new_computer.md'
    - Purchasing: 'getting_started/purchasing.md'
  - Computing:
    - General Info: 'computing/computing.md'
    - Software: 'computing/software.md'
    - HPC: 'computing/hpc.md'
    - Atomate Setup: 'computing/atomate.md'
    - Calculation Software: 'computing/calculation_software.md'
  - Students:
    - Establishing Residency: 'students/residency.md'
    - Preparing for Prelims: 'students/prelims.md'
    - Qualifying Exams: 'students/qualifying.md'
  - Post-Docs: 'postdocs.md'
  - Acknowlegements: 'acknowlegements.md'

markdown_extensions:
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'

extra_css:
  - 'css/code-tabs.css'
